# Generated by Django 5.0.6 on 2024-06-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('type', models.CharField(choices=[('1', 'Полная ставка'), ('0.5', 'Неполная')], default='1', max_length=50, verbose_name='Ставка')),
                ('character', models.TextField(max_length=100, verbose_name='Должность')),
                ('price', models.IntegerField(max_length=50, verbose_name='Зарплата')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'список сотрудников',
            },
        ),
    ]
