# Generated by Django 5.0.6 on 2024-06-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='character',
            field=models.TextField(max_length=100, verbose_name='Должность и описание'),
        ),
    ]
