# Generated by Django 5.0.6 on 2024-06-06 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0005_office_alter_staff_character_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.staff'),
        ),
    ]
