# Generated by Django 5.0.6 on 2024-06-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0006_alter_application_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='price',
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.CharField(max_length=20, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='application',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.staff', verbose_name='Выберите сотрудника'),
        ),
    ]
